import type { NextPage } from "next";
import Head from "next/head";
import data from "../data/data.json";
import { NetworkGraphRFG } from "../components/NetworkGraphRFG";

const Home: NextPage = () => {
  return (
    <div className="bg-gray-900 h-full w-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>{NetworkGraphRFG(data)}</main>

      <footer></footer>
    </div>
  );
};

export default Home;
